#Basd on the latest ubuntu
FROM ubuntu:latest

#Update APT using apt-get update
#Upgrade currently installed software through APT using apt-get upgrade -y
RUN apt-get update && apt-get upgrade -y

CMD ["echo", "Hello, World!"]
