services:
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy:task5
    ports:
    - "80:80"
    depends_on:
      - back-end
      - front-end
